### ISSUE TITLE
Pipeline failed because worker has been reported dead

### ISSUE THREAD

**Issue by gprinz** [tarrade/proj_NLP_text_classification_with_GCP#23] opened 2019-11-19 15:43 UTC
![image](https://user-images.githubusercontent.com/32190139/69161474-8305a900-0aeb-11ea-805b-47a60308e4ad.png)

**Comment by gprinz** [comment] 2019-11-19 15:59
Work item failed because worker was not able to access temp folder in Cloud Storage.

**Comment by tarrade** [comment] 2019-11-20 11:08
I am not sure I fully understand the distribution of the number of element processed:
![image](https://user-images.githubusercontent.com/12021701/69233711-b436b580-0b8d-11ea-9748-69a372431214.png)
![image](https://user-images.githubusercontent.com/12021701/69233738-c1ec3b00-0b8d-11ea-882f-4b9974752d86.png)

My price estimation was wrong by a factor 2 but this ok. It could be that we have some very long post and that this is not uniformly distributed over time.

**Comment by tarrade** [comment] 2019-11-20 11:20
The issue is very obscur to me:
```
An exception was raised when trying to execute the workitem 3375186074549785796 : Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/dataflow_worker/batchworker.py", line 649, in do_work
    work_executor.execute()
  File "/usr/local/lib/python3.6/site-packages/dataflow_worker/executor.py", line 176, in execute
    op.start()
  File "dataflow_worker/native_operations.py", line 38, in dataflow_worker.native_operations.NativeReadOperation.start
  File "dataflow_worker/native_operations.py", line 39, in dataflow_worker.native_operations.NativeReadOperation.start
  File "dataflow_worker/native_operations.py", line 44, in dataflow_worker.native_operations.NativeReadOperation.start
  File "dataflow_worker/native_operations.py", line 48, in dataflow_worker.native_operations.NativeReadOperation.start
  File "/usr/local/lib/python3.6/site-packages/dataflow_worker/nativefileio.py", line 204, in __iter__
    for record in self.read_next_block():
  File "/usr/local/lib/python3.6/site-packages/dataflow_worker/nativeavroio.py", line 198, in read_next_block
    fastavro_block = next(self._block_iterator)
  File "fastavro/_read.pyx", line 738, in fastavro._read.file_reader.next
  File "fastavro/_read.pyx", line 662, in _iter_avro_blocks
  File "fastavro/_read.pyx", line 595, in fastavro._read.null_read_block
  File "fastavro/_read.pyx", line 597, in fastavro._read.null_read_block
  File "fastavro/_read.pyx", line 304, in fastavro._read.read_bytes
  File "/usr/local/lib/python3.6/site-packages/apache_beam/io/filesystemio.py", line 113, in readinto
    data = self._downloader.get_range(start, end)
  File "/usr/local/lib/python3.6/site-packages/apache_beam/io/gcp/gcsio.py", line 522, in get_range
    self._downloader.GetRange(start, end - 1)
  File "/usr/local/lib/python3.6/site-packages/apitools/base/py/transfer.py", line 486, in GetRange
    response = self.__ProcessResponse(response)
  File "/usr/local/lib/python3.6/site-packages/apitools/base/py/transfer.py", line 424, in __ProcessResponse
    raise exceptions.HttpError.FromResponse(response)
apitools.base.py.exceptions.HttpNotFoundError: HttpError accessing <https://www.googleapis.com/storage/v1/b/nlp-text-classification/o/beam%2Ftemp%2Fstackoverflow-raphael-191119-084402.1574153042.687677%2F11710707918635668555%2F000000000023.avro?alt=media&generation=1574154195414240>: response: <{'x-guploader-uploadid': 'AEnB2UpfZyD4QD27z0MiT48cgNxshu54CKcKGE1mvdPMxpsXYBq2FtLdwgnWzb5XYAiy3u-RhpPmNrtKk4aI9epGJBolCGV_PQ', 'content-type': 'text/html; charset=UTF-8', 'date': 'Tue, 19 Nov 2019 15:28:15 GMT', 'vary': 'Origin, X-Origin', 'expires': 'Tue, 19 Nov 2019 15:28:15 GMT', 'cache-control': 'private, max-age=0', 'content-length': '142', 'server': 'UploadServer', 'status': '404'}>, content <No such object: nlp-text-classification/beam/temp/stackoverflow-raphael-191119-084402.1574153042.687677/11710707918635668555/000000000023.avro>

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/dataflow_worker/batchworker.py", line 649, in do_work
    work_executor.execute()
  File "/usr/local/lib/python3.6/site-packages/dataflow_worker/executor.py", line 176, in execute
    op.start()
  File "dataflow_worker/native_operations.py", line 38, in dataflow_worker.native_operations.NativeReadOperation.start
  File "dataflow_worker/native_operations.py", line 39, in dataflow_worker.native_operations.NativeReadOperation.start
  File "dataflow_worker/native_operations.py", line 44, in dataflow_worker.native_operations.NativeReadOperation.start
  File "dataflow_worker/native_operations.py", line 48, in dataflow_worker.native_operations.NativeReadOperation.start
  File "/usr/local/lib/python3.6/site-packages/dataflow_worker/nativefileio.py", line 204, in __iter__
    for record in self.read_next_block():
  File "/usr/local/lib/python3.6/site-packages/dataflow_worker/nativeavroio.py", line 198, in read_next_block
    fastavro_block = next(self._block_iterator)
  File "fastavro/_read.pyx", line 738, in fastavro._read.file_reader.next
  File "fastavro/_read.pyx", line 662, in _iter_avro_blocks
  File "fastavro/_read.pyx", line 595, in fastavro._read.null_read_block
  File "fastavro/_read.pyx", line 597, in fastavro._read.null_read_block
  File "fastavro/_read.pyx", line 304, in fastavro._read.read_bytes
  File "/usr/local/lib/python3.6/site-packages/apache_beam/io/filesystemio.py", line 113, in readinto
    data = self._downloader.get_range(start, end)
  File "/usr/local/lib/python3.6/site-packages/apache_beam/io/gcp/gcsio.py", line 522, in get_range
    self._downloader.GetRange(start, end - 1)
  File "/usr/local/lib/python3.6/site-packages/apitools/base/py/transfer.py", line 486, in GetRange
    response = self.__ProcessResponse(response)
  File "/usr/local/lib/python3.6/site-packages/apitools/base/py/transfer.py", line 424, in __ProcessResponse
    raise exceptions.HttpError.FromResponse(response)
apitools.base.py.exceptions.HttpNotFoundError: HttpError accessing <https://www.googleapis.com/storage/v1/b/nlp-text-classification/o/beam%2Ftemp%2Fstackoverflow-raphael-191119-084402.1574153042.687677%2F11710707918635668555%2F000000000023.avro?alt=media&generation=1574154195414240>: response: <{'x-guploader-uploadid': 'AEnB2UpfZyD4QD27z0MiT48cgNxshu54CKcKGE1mvdPMxpsXYBq2FtLdwgnWzb5XYAiy3u-RhpPmNrtKk4aI9epGJBolCGV_PQ', 'content-type': 'text/html; charset=UTF-8', 'date': 'Tue, 19 Nov 2019 15:28:15 GMT', 'vary': 'Origin, X-Origin', 'expires': 'Tue, 19 Nov 2019 15:28:15 GMT', 'cache-control': 'private, max-age=0', 'content-length': '142', 'server': 'UploadServer', 'status': '404'}>, content <No such object: nlp-text-classification/beam/temp/stackoverflow-raphael-191119-084402.1574153042.687677/11710707918635668555/000000000023.avro>
timestamp	
2019-11-19T15:28:15.939456462Z
logger	
root:batchworker.py:do_work
severity	
ERROR
worker	
stackoverflow-raphael-191-11190044-7wyy-harness-0hvf
step	
Read Posts from BigQuery
thread	
73:139970017903616
```
I don't like this retry every 2-3 second. It doesn't seems very good:
![image](https://user-images.githubusercontent.com/12021701/69234158-b9483480-0b8e-11ea-82a9-d2351101c4d6.png)

There is this related issue:

```
one of the 4 failures. For more information, see https://cloud.google.com/dataflow/docs/guides/common-errors. The work item was attempted on these workers: 
  stackoverflow-raphael-191-11190044-7wyy-harness-lcpj
      Root cause: Work item failed.,
  stackoverflow-raphael-191-11190044-7wyy-harness-nnjv
      Root cause: The worker lost contact with the service.,
  stackoverflow-raphael-191-11190044-7wyy-harness-wrvl
      Root cause: The worker lost contact with the service.,
  stackoverflow-raphael-191-11190044-7wyy-harness-88z8
      Root cause: The worker stackoverflow-raphael-191-11190044-7wyy-harness-88z8 has been reported dead. Aborting lease 2143143934289914405.
```

I am not sure which one happened first. It maybe a transient issue but I am to be sure that there is no other parameters to tunes like the number of retry (4) or the number of failure we can accepts.

**Comment by gprinz** [comment] 2019-11-20 13:03
In batch mode, there is no option to load the elements processed by the worker pool continuously into BigQuery: [](https://stackoverflow.com/questions/50763529/dataflow-can-i-write-continuously-stream-write-to-bigquery-with-batch-job) Accordingly, if a job fails, the data gets lost (besides the data written to Cloud Storage).

**Comment by gprinz** [comment] 2019-11-20 13:30
I have posted the problem on stackoverflow (https://stackoverflow.com/questions/58955481/dataflow-jb-failed-due-to-httpnotfounderror) and hope that someone of the Google team has an idea. I have no clue what might have had caused the problem.

**Comment by tarrade** [comment] 2019-11-20 14:04
Got the same idea and it took me 1 hours to summarize it. I look at it from a different view than your by looking at the timestamo of the messages:
https://stackoverflow.com/questions/58956171/dataflow-job-failed-after-more-than-6-hours-with-the-worker-lost-contact-with-t

Let see if you got an answer. I am not sure people will understand my huge post.

**Comment by gprinz** [comment] 2019-11-20 16:51
@tarrade Google's DataFlow team is watching posts with the tag 'google-cloud-dataflow'. Otherwise, we can contact dataflow-feedback@google.com to ask for advise.

**Comment by tarrade** [comment] 2019-11-21 06:40
yes, our only option is if GCP Dataflow team is watching our tickets. We cannot open a case to GCP because we use a private account. Please downvote on both ticket this suggestion from the same personnn that did the same comment on our post ;-) This is not an answer. What I am 100% sure is that workers are dying. The question is why: bad luck or GCP pb or because of memory/disk issue but here I need guidance.

**Comment by gprinz** [comment] 2019-11-21 07:56
@tarrade My suggestion: Increase the quota for the disk space (could you do that?) and re-run the job next Monday on the subset if we do no get an answer from the developers.

I know that support is not an option. Do you have any direct contact to the Google team we could use?

**Comment by tarrade** [comment] 2019-11-21 09:24
I increase the disk size from 6'144 GB to 25'600 GB so we should be able to use  250 GB (default) per VM. I also requested 120 CPUs globaly to have 100 workers.

Let see if we get some feedback today. If not, just rerun the full dataset on Friday  morning (like start at 9:00 am so we can look what append during the day.

**Comment by tarrade** [comment] 2019-11-26 17:20
we believe it related to memory leak from SpaCy. Discussion in other ticket. Closing for now

**Closed by tarrade** 2019-11-26 17:20 UTC
